export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  "a sea otter with a pearl earring by Johannes Vermeer",
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "  alternate reality alien creature like a Van Gogh painting",
  "alternate reality cat in the style of Studio Ghibli",
  "alternate reality cityscape as a LEGO diorama",
  "alternate reality enchanted tree as a ukiyo-e print",
  "alternate reality floating temple as claymation",
  "alternate reality giant mushroom like a retro postcard",
  "alternate reality interior room in ink and wash",
  "alternate reality library as a stained glass window",
  "alternate reality mechanical bird in the style of Art Nouveau",
  "alternate reality ocean floor like a surrealist collage",
  "ancient civilization cat in ink and wash",
  "ancient civilization cityscape as a LEGO diorama",
  "ancient civilization interior room like a Van Gogh painting",
  "ancient civilization library in watercolor",
  "ancient civilization ocean floor in pixel art",
  "ancient civilization quantum computer as LEGO diorama",
  "ancient civilization robot in the style of Studio Ghibli",
  "ancient civilization sky whale in graffiti style",
  "ancient civilization spaceship as a comic book page",
  "ancient civilization time travel as LEGO diorama",
  "Baroque cat like a retro postcard",
  "Baroque cityscape in the style of Art Nouveau",
  "Baroque enchanted tree in the style of Studio Ghibli",
  "Baroque floating temple in watercolor",
  "Baroque interior room like a Van Gogh painting",
  "Baroque mountain range as LEGO diorama",
  "Baroque ocean floor in graffiti style",
  "Baroque phantom train as LEGO diorama",
  "Baroque portal like a surrealist collage",
  "Baroque spaceship as a comic book page",
  "cosmic alien creature in the style of Art Nouveau",
  "cosmic castle as LEGO diorama",
  "cosmic dragon in pixel art",
  "cosmic enchanted tree like a surrealist collage",
  "cosmic floating island like a Van Gogh painting",
  "cosmic mechanical bird in the style of Studio Ghibli",
  "cosmic mountain range as a stained glass window",
  "cosmic robot in graffiti style",
  "cosmic sky whale in ink and wash",
  "cosmic spaceship as a comic book page",
  "cyberpunk alien creature in graffiti style",
  "cyberpunk cityscape as claymation",
  "cyberpunk enchanted tree as a stained glass window",
  "cyberpunk floating island as LEGO diorama",
  "cyberpunk interior room like a surrealist collage",
  "cyberpunk mechanical bird like a retro postcard",
  "cyberpunk ocean floor in ink and wash",
  "cyberpunk phantom train as a ukiyo-e print",
  "cyberpunk portal like a Van Gogh painting",
  "cyberpunk quantum computer in the style of Art Nouveau",
  "desert oasis alien creature in pixel art",
  "desert oasis castle in graffiti style",
  "desert oasis cityscape in the style of Art Nouveau",
  "desert oasis dragon in ink and wash",
  "desert oasis enchanted tree like a Van Gogh painting",
  "desert oasis floating temple as a stained glass window",
  "desert oasis interior room as LEGO diorama",
  "desert oasis mountain range as a comic book page",
  "desert oasis portal in the style of Studio Ghibli",
  "desert oasis spaceship as claymation",
  "dreamlike cat as a ukiyo-e print",
  "dreamlike cityscape like a retro postcard",
  "dreamlike dragon like a surrealist collage",
  "dreamlike enchanted tree in graffiti style",
  "dreamlike floating island in the style of Art Nouveau",
  "dreamlike interior room as LEGO diorama",
  "dreamlike mechanical bird in ink and wash",
  "dreamlike mountain range like a Van Gogh painting",
  "dreamlike sky whale in pixel art",
  "dreamlike spaceship in watercolor",
  "fantasy alien creature in graffiti style",
  "fantasy castle in watercolor",
  "fantasy cat like a Van Gogh painting",
  "fantasy dragon in the style of Studio Ghibli",
  "fantasy enchanted tree as a stained glass window",
  "fantasy floating island in the style of Art Nouveau",
  "fantasy interior room in pixel art",
  "fantasy portal as a comic book page",
  "fantasy robot like a surrealist collage",
  "fantasy sky whale in ink and wash",
  "floating island cat as a stained glass window",
  "floating island interior room in ink and wash",
  "floating island mountain range like a retro postcard",
  "floating island phantom train like a surrealist collage",
  "floating island portal as LEGO diorama",
  "floating island robot as claymation",
  "floating island sky whale in watercolor",
  "floating island spaceship in graffiti style",
  "floating island time travel in pixel art",
  "floating island quantum computer as a comic book page",
  "futuristic alien creature in pixel art",
  "futuristic castle as LEGO diorama",
  "futuristic cityscape in graffiti style",
  "futuristic dragon like a surrealist collage",
  "futuristic enchanted tree as a ukiyo-e print",
  "futuristic mechanical bird in ink and wash",
  "futuristic mountain range in the style of Art Nouveau",
  "futuristic portal as a comic book page",
  "futuristic quantum computer like a Van Gogh painting",
  "futuristic spaceship in watercolor",
  "mechanical bird like a surrealist collage",
  "minimalist alien creature in the style of Art Nouveau",
  "minimalist cat as claymation",
  "minimalist cityscape like a retro postcard",
  "minimalist dragon as LEGO diorama",
  "minimalist enchanted tree in pixel art",
  "minimalist interior room in graffiti style",
  "minimalist mountain range in ink and wash",
  "minimalist ocean floor as a comic book page",
  "minimalist phantom train in the style of Studio Ghibli",
  "minimalist portal in watercolor",
  "mystical forest alien creature in ink and wash",
  "mystical forest castle as a comic book page",
  "mystical forest dragon in pixel art",
  "mystical forest floating island as LEGO diorama",
  "mystical forest interior room in graffiti style",
  "mystical forest ocean floor as a stained glass window",
  "mystical forest portal like a surrealist collage",
  "mystical forest robot as a ukiyo-e print",
  "mystical forest sky whale in the style of Art Nouveau",
  "mystical forest spaceship like a retro postcard",
  "neon-lit cat in the style of Studio Ghibli",
  "neon-lit enchanted tree in watercolor",
  "neon-lit floating island in graffiti style",
  "neon-lit interior room like a Van Gogh painting",
  "neon-lit library as LEGO diorama",
  "neon-lit ocean floor as a stained glass window",
  "neon-lit portal in ink and wash",
  "neon-lit robot like a surrealist collage",
  "neon-lit spaceship as a comic book page",
  "neon-lit time travel in the style of Art Nouveau",
  "parallel universe alien creature like a surrealist collage",
  "parallel universe cityscape in pixel art",
  "parallel universe enchanted tree in the style of Studio Ghibli",
  "parallel universe interior room like a retro postcard",
  "parallel universe mechanical bird as LEGO diorama",
  "parallel universe mountain range in the style of Art Nouveau",
  "parallel universe ocean floor in ink and wash",
  "parallel universe phantom train as a comic book page",
  "parallel universe quantum computer in watercolor",
  "parallel universe spaceship in graffiti style",
  "phantom train in the style of Studio Ghibli",
  "post-apocalyptic alien creature like a Van Gogh painting",
  "post-apocalyptic cat as a comic book page",
  "post-apocalyptic dragon in graffiti style",
  "post-apocalyptic enchanted tree as LEGO diorama",
  "post-apocalyptic floating island in pixel art",
  "post-apocalyptic mechanical bird like a surrealist collage",
  "post-apocalyptic mountain range as a stained glass window",
  "post-apocalyptic portal in the style of Art Nouveau",
  "post-apocalyptic robot in watercolor",
  "post-apocalyptic spaceship like a retro postcard",
  "retro-futurism alien creature in the style of Studio Ghibli",
  "retro-futurism castle like a surrealist collage",
  "retro-futurism cat as LEGO diorama",
  "retro-futurism dragon in ink and wash",
  "retro-futurism floating island as a stained glass window",
  "retro-futurism mechanical bird in graffiti style",
  "retro-futurism ocean floor in the style of Art Nouveau",
  "retro-futurism portal as claymation",
  "retro-futurism robot in pixel art",
  "retro-futurism sky whale like a Van Gogh painting",
  "robotic alien creature like a retro postcard",
  "robotic cat like a surrealist collage",
  "robotic cityscape as claymation",
  "robotic enchanted tree in the style of Studio Ghibli",
  "robotic floating island in ink and wash",
  "robotic mechanical bird as a comic book page",
  "robotic portal in watercolor",
  "robotic robot in graffiti style",
  "robotic spaceship in pixel art",
  "robotic time travel as LEGO diorama",
  "sci-fi cat like a Van Gogh painting",
  "sci-fi castle as a ukiyo-e print",
  "sci-fi cityscape in the style of Art Nouveau",
  "sci-fi enchanted tree like a surrealist collage",
  "sci-fi floating island in pixel art",
  "sci-fi interior room as a comic book page",
  "sci-fi portal in ink and wash",
  "sci-fi robot as LEGO diorama",
  "sci-fi sky whale in watercolor",
  "sci-fi spaceship in graffiti style",
  "sky whale as a stained glass window",
  "steampunk alien creature in pixel art",
  "steampunk castle like a Van Gogh painting",
  "steampunk enchanted tree in the style of Studio Ghibli",
  "steampunk floating island as LEGO diorama",
  "steampunk interior room like a retro postcard",
  "steampunk ocean floor in graffiti style",
  "steampunk portal in watercolor",
  "steampunk robot as a comic book page",
  "steampunk spaceship like a surrealist collage",
  "steampunk time travel in the style of Art Nouveau",
  "surreal floating temple as claymation",
  "surreal giant mushroom in graffiti style",
  "surreal library in pixel art",
  "surreal mountain range like a surrealist collage",
  "surreal ocean floor as a ukiyo-e print",
  "surreal portal in watercolor",
  "surreal robot in the style of Studio Ghibli",
  "surreal sky whale in ink and wash",
  "surreal spaceship as LEGO diorama",
  "surreal time travel like a Van Gogh painting",
  "time travel cat as a stained glass window",
  "time travel castle like a retro postcard",
  "time travel enchanted tree in the style of Studio Ghibli",
  "time travel interior room in pixel art",
  "time travel library in the style of Studio Ghibli",
  "time travel mechanical bird like a surrealist collage",
  "time travel mountain range as LEGO diorama",
  "time travel portal in graffiti style",
  "time travel quantum computer in watercolor",
  "time travel spaceship in ink and wash",
  "underwater cat in watercolor",
  "underwater cityscape in the style of Art Nouveau",
  "underwater enchanted tree as a comic book page",
  "underwater floating island like a retro postcard",
  "underwater mechanical bird in graffiti style",
  "underwater ocean floor in the style of Studio Ghibli",
  "underwater portal like a Van Gogh painting",
  "underwater robot in ink and wash",
  "underwater sky whale in pixel art",
  "underwater spaceship as LEGO diorama",
  "urban dystopia alien creature as a ukiyo-e print",
  "urban dystopia cityscape as a stained glass window",
  "urban dystopia dragon in pixel art",
  "urban dystopia enchanted tree in graffiti style",
  "urban dystopia giant mushroom in ink and wash",
  "urban dystopia library as a comic book page",
  "urban dystopia portal in the style of Studio Ghibli",
  "urban dystopia robot like a Van Gogh painting",
  "urban dystopia spaceship as LEGO diorama",
  "urban dystopia sky whale in watercolor",
];
